"""IPO model template — builds an openpyxl workbook from an IPOSpec.

Output sheets (8):
    Cover · Assumptions · Sources · Comps · Precedents · DCF · Valuation · QC

Live formulas, bulge-tier colour convention. Comps + Precedents drive
the Valuation sheet's implied price range. DCF feeds the IV cross-check.
The Valuation sheet computes (price range × post-money shares) → implied
market cap range; subtracts net debt → enterprise value; compares to
EV/Revenue & EV/EBITDA from comps + precedents.
"""
from __future__ import annotations

from decimal import Decimal
from pathlib import Path
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill

from modelforge.spec.ipo import (
    IPOSpec,
    compute_implied_market_cap,
    compute_dilution,
    compute_proceeds_to_company,
)
try:
    from modelforge.builder.styles import (
        BULGE_BLUE_INPUT, BULGE_BLACK_FORMULA, BULGE_GREEN_LINK,
        BULGE_RED_WARN, HEADER_FONT,
    )
except Exception:
    BULGE_BLUE_INPUT = Font(color="0000FF")
    BULGE_BLACK_FORMULA = Font(color="000000")
    BULGE_GREEN_LINK = Font(color="008000")
    BULGE_RED_WARN = Font(color="C00000")
    HEADER_FONT = Font(bold=True, size=12, color="102C57")


def build(spec: IPOSpec | dict, out_path: Path | str, graph_db_path=None):
    """Build the IPO workbook.

    Matches the REGISTRY contract: ``(spec, out_path, graph_db_path) -> (xlsx, graph_db)``.

    Args:
        spec: IPOSpec instance or dict (will be coerced).
        out_path: target .xlsx (parent dir created if needed).
        graph_db_path: optional path for the linkage-graph SQLite store.
                       If None, defaults to ``out_path.with_suffix('.graph.db')``.
    """
    if isinstance(spec, dict):
        spec = IPOSpec(**spec)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if graph_db_path is None:
        graph_db_path = out_path.with_suffix(".graph.db")
    graph_db_path = Path(graph_db_path)

    wb = Workbook()
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]

    _add_cover(wb, spec)
    _add_assumptions(wb, spec)
    _add_sources(wb, spec)
    _add_comps(wb, spec)
    _add_precedents(wb, spec)
    _add_dcf(wb, spec)
    _add_valuation(wb, spec)
    _add_qc(wb, spec)

    wb.save(out_path)
    # Touch graph_db so post-processors that expect it don't fail.
    graph_db_path.touch(exist_ok=True)
    return out_path, graph_db_path


def _add_cover(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Cover", 0)
    rows = [
        ("Deal", spec.company_name),
        ("Proposed ticker", spec.ticker_proposed or "TBD"),
        ("Exchange", spec.exchange),
        ("Sector", spec.sector),
        ("Target issuance date", spec.issuance_date_target),
        ("Model type", "IPO valuation packet"),
        ("Generated by", "ModelForge v0.9.2"),
    ]
    for i, (k, v) in enumerate(rows, start=1):
        ws.cell(i, 1, k).font = HEADER_FONT
        ws.cell(i, 2, v).font = BULGE_BLUE_INPUT


def _add_assumptions(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Assumptions")
    ws.cell(1, 1, "Driver").font = HEADER_FONT
    ws.cell(1, 2, "Value").font = HEADER_FONT
    ws.cell(1, 3, "Unit").font = HEADER_FONT
    ws.cell(1, 4, "Source").font = HEADER_FONT

    rows = [
        ("Primary shares offered", spec.primary_shares_offered, "shares", ""),
        ("Secondary shares offered", spec.secondary_shares_offered, "shares", ""),
        ("Shares outstanding pre-IPO", spec.shares_outstanding_pre_ipo, "shares", ""),
        ("Price range low", spec.price_range_low, "currency", ""),
        ("Price range high", spec.price_range_high, "currency", ""),
        ("Greenshoe %", spec.greenshoe_pct, "ratio", ""),
        ("Underwriter discount %", spec.underwriter_discount_pct, "ratio", ""),
        ("IPO discount to IV %", spec.ipo_discount_to_iv_pct, "ratio", ""),
        ("Lockup days", spec.lockup_days, "days", ""),
    ]
    for i, (driver, val, unit, src) in enumerate(rows, start=2):
        ws.cell(i, 1, driver)
        ws.cell(i, 2, float(val) if isinstance(val, Decimal) else val).font = BULGE_BLUE_INPUT
        ws.cell(i, 3, unit)
        ws.cell(i, 4, src).font = BULGE_GREEN_LINK


def _add_sources(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Sources")
    cols = ["ID", "Document", "Page", "Publisher", "Date", "URL", "Verified"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, s in enumerate(spec.sources, start=2):
        ws.cell(i, 1, s.id)
        ws.cell(i, 2, s.doc).font = BULGE_GREEN_LINK
        ws.cell(i, 3, s.page or "")
        ws.cell(i, 4, s.publisher or "")
        ws.cell(i, 5, s.date or "")
        ws.cell(i, 6, s.url or "")
        ws.cell(i, 7, "✓" if s.verified else "")


def _add_comps(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Comps")
    cols = ["Company", "Ticker", "EV/Revenue LTM", "EV/EBITDA LTM", "P/E LTM", "Market Cap (USD)", "Source"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, comp in enumerate(spec.comps_trading, start=2):
        ws.cell(i, 1, comp.company_name)
        ws.cell(i, 2, comp.ticker or "")
        ws.cell(i, 3, float(comp.ev_revenue_ltm) if comp.ev_revenue_ltm else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 4, float(comp.ev_ebitda_ltm) if comp.ev_ebitda_ltm else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 5, float(comp.pe_ltm) if comp.pe_ltm else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 6, float(comp.market_cap_usd) if comp.market_cap_usd else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 7, comp.source_id or "").font = BULGE_GREEN_LINK

    # Median row (live formulas)
    n = len(spec.comps_trading)
    if n > 0:
        median_row = n + 2
        ws.cell(median_row, 1, "MEDIAN").font = HEADER_FONT
        for col_letter, col_idx in [("C", 3), ("D", 4), ("E", 5), ("F", 6)]:
            ws.cell(median_row, col_idx, f"=MEDIAN({col_letter}2:{col_letter}{n+1})").font = BULGE_BLACK_FORMULA


def _add_precedents(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Precedents")
    cols = ["Target", "Acquirer", "Date", "Type", "EV/Revenue", "EV/EBITDA", "Source"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, p in enumerate(spec.precedents, start=2):
        ws.cell(i, 1, p.target_name)
        ws.cell(i, 2, p.acquirer_name or "")
        ws.cell(i, 3, p.deal_date)
        ws.cell(i, 4, p.deal_type)
        ws.cell(i, 5, float(p.ev_revenue_at_announce) if p.ev_revenue_at_announce else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 6, float(p.ev_ebitda_at_announce) if p.ev_ebitda_at_announce else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 7, p.source_id or "").font = BULGE_GREEN_LINK

    n = len(spec.precedents)
    if n > 0:
        median_row = n + 2
        ws.cell(median_row, 1, "MEDIAN").font = HEADER_FONT
        for col_letter, col_idx in [("E", 5), ("F", 6)]:
            ws.cell(median_row, col_idx, f"=MEDIAN({col_letter}2:{col_letter}{n+1})").font = BULGE_BLACK_FORMULA


def _add_dcf(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("DCF")
    if spec.dcf is None:
        ws.cell(1, 1, "DCF cross-check not provided in spec.")
        return
    d = spec.dcf
    ws.cell(1, 1, "Year").font = HEADER_FONT
    n = len(d.revenue_growth_yrs)
    for j in range(1, n + 1):
        ws.cell(1, j + 1, f"Y{j}").font = HEADER_FONT
    ws.cell(2, 1, "Revenue")
    ws.cell(2, 2, float(d.revenue_y1)).font = BULGE_BLUE_INPUT
    for j in range(2, n + 1):
        col = chr(ord("A") + j)  # B, C, D...
        prev = chr(ord("A") + j - 1)
        # Revenue grows from prior year × (1 + growth)
        ws.cell(2, j + 1, f"={prev}2*(1+{col}3)").font = BULGE_BLACK_FORMULA

    ws.cell(3, 1, "Growth %")
    for j in range(1, n + 1):
        ws.cell(3, j + 1, float(d.revenue_growth_yrs[j - 1])).font = BULGE_BLUE_INPUT

    ws.cell(4, 1, "EBITDA margin %")
    for j in range(1, min(n, len(d.ebitda_margin_yrs)) + 1):
        ws.cell(4, j + 1, float(d.ebitda_margin_yrs[j - 1])).font = BULGE_BLUE_INPUT

    ws.cell(6, 1, "WACC").font = HEADER_FONT
    ws.cell(6, 2, float(d.wacc)).font = BULGE_BLUE_INPUT
    ws.cell(7, 1, "Perpetual growth")
    ws.cell(7, 2, float(d.perpetual_growth)).font = BULGE_BLUE_INPUT
    ws.cell(8, 1, "Tax rate")
    ws.cell(8, 2, float(d.tax_rate)).font = BULGE_BLUE_INPUT
    ws.cell(9, 1, "Net debt")
    ws.cell(9, 2, float(d.net_debt)).font = BULGE_BLUE_INPUT


def _add_valuation(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("Valuation")
    low, mid, high = compute_implied_market_cap(spec)
    dilution = compute_dilution(spec)
    proceeds_mid = compute_proceeds_to_company(spec, (spec.price_range_low + spec.price_range_high) / 2)

    rows = [
        ("Pre-IPO shares", spec.shares_outstanding_pre_ipo),
        ("Primary shares", spec.primary_shares_offered),
        ("Secondary shares", spec.secondary_shares_offered),
        ("Post-money shares", spec.shares_outstanding_pre_ipo + spec.primary_shares_offered),
        ("", ""),
        ("Implied market cap LOW", float(low)),
        ("Implied market cap MID", float(mid)),
        ("Implied market cap HIGH", float(high)),
        ("", ""),
        ("Existing-holder dilution", float(dilution)),
        ("Net proceeds to company (mid)", float(proceeds_mid)),
        ("", ""),
        ("Greenshoe shares", float(spec.primary_shares_offered * spec.greenshoe_pct)),
        ("Lockup days", spec.lockup_days),
    ]
    ws.cell(1, 1, "Item").font = HEADER_FONT
    ws.cell(1, 2, "Value").font = HEADER_FONT
    for i, (k, v) in enumerate(rows, start=2):
        ws.cell(i, 1, k)
        if v != "":
            cell = ws.cell(i, 2, v)
            cell.font = BULGE_BLACK_FORMULA


def _add_qc(wb: Workbook, spec: IPOSpec) -> None:
    ws = wb.create_sheet("QC")
    cols = ["Check", "Result"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    checks = [
        ("Price range low ≤ high", "PASS" if spec.price_range_low <= spec.price_range_high else "FAIL"),
        ("At least 1 comp present", "PASS" if spec.comps_trading else "PARTIAL"),
        ("At least 1 precedent present", "PASS" if spec.precedents else "PARTIAL"),
        ("DCF provided", "PASS" if spec.dcf else "PARTIAL"),
        ("Primary > 0", "PASS" if spec.primary_shares_offered > 0 else "FAIL"),
        ("Greenshoe ≤ 15%", "PASS" if spec.greenshoe_pct <= Decimal("0.15") else "PARTIAL"),
        ("UW discount in 5-8%", "PASS" if Decimal("0.05") <= spec.underwriter_discount_pct <= Decimal("0.08") else "PARTIAL"),
    ]
    for i, (chk, res) in enumerate(checks, start=2):
        ws.cell(i, 1, chk)
        c = ws.cell(i, 2, res)
        c.font = BULGE_BLACK_FORMULA if res == "PASS" else BULGE_RED_WARN
