"""Restructuring / Chapter 11 model template.

Output sheets (8):
    Cover · Assumptions · Sources · Claims · DIP · Waterfall · PlanRecoveries · QC

Live formulas. The Waterfall sheet implements absolute-priority distribution
of enterprise value to claim classes in priority order. PlanRecoveries
captures the deal-specific allocation (which may violate APR via consent).
"""
from __future__ import annotations

from decimal import Decimal
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font

from modelforge.spec.restructuring import (
    RestructuringSpec,
    compute_absolute_priority_waterfall,
    compute_total_dip_cost,
)

try:
    from modelforge.builder.styles import (
        BULGE_BLUE_INPUT, BULGE_BLACK_FORMULA, BULGE_GREEN_LINK,
        BULGE_RED_WARN, HEADER_FONT,
    )
except Exception:
    BULGE_BLUE_INPUT = Font(color="0000FF")
    BULGE_BLACK_FORMULA = Font(color="000000")
    BULGE_GREEN_LINK = Font(color="008000")
    BULGE_RED_WARN = Font(color="C00000")
    HEADER_FONT = Font(bold=True, size=12, color="102C57")


def build(spec: RestructuringSpec | dict, out_path: Path | str, graph_db_path=None):
    """Build the restructuring workbook.

    Matches REGISTRY contract: ``(spec, out_path, graph_db_path) -> (xlsx, graph_db)``.
    """
    if isinstance(spec, dict):
        spec = RestructuringSpec(**spec)

    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    if graph_db_path is None:
        graph_db_path = out_path.with_suffix(".graph.db")
    graph_db_path = Path(graph_db_path)

    wb = Workbook()
    if "Sheet" in wb.sheetnames:
        del wb["Sheet"]

    _cover(wb, spec)
    _assumptions(wb, spec)
    _sources(wb, spec)
    _claims(wb, spec)
    _dip(wb, spec)
    _waterfall(wb, spec)
    _plan(wb, spec)
    _qc(wb, spec)

    wb.save(out_path)
    graph_db_path.touch(exist_ok=True)
    return out_path, graph_db_path


def _cover(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("Cover", 0)
    rows = [
        ("Debtor", spec.debtor_name),
        ("Case number", spec.case_number or "TBD"),
        ("Jurisdiction", spec.jurisdiction),
        ("Filing date", spec.filing_date),
        ("Months in Ch. 11", spec.months_in_chapter11),
        ("Confirmation target", spec.confirmation_date_target),
        ("Model type", "Restructuring / Plan of Reorganization"),
        ("Generated by", "ModelForge v0.9.2"),
    ]
    for i, (k, v) in enumerate(rows, start=1):
        ws.cell(i, 1, k).font = HEADER_FONT
        ws.cell(i, 2, v).font = BULGE_BLUE_INPUT


def _assumptions(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("Assumptions")
    ws.cell(1, 1, "Driver").font = HEADER_FONT
    ws.cell(1, 2, "Value").font = HEADER_FONT
    ws.cell(1, 3, "Unit").font = HEADER_FONT
    rows = [
        ("Enterprise value post-emergence", float(spec.enterprise_value_post), "currency"),
        ("Cash at emergence", float(spec.cash_at_emergence), "currency"),
        ("New debt at emergence", float(spec.new_debt_at_emergence), "currency"),
        ("Months in Chapter 11", spec.months_in_chapter11, "months"),
    ]
    for i, (k, v, u) in enumerate(rows, start=2):
        ws.cell(i, 1, k)
        ws.cell(i, 2, v).font = BULGE_BLUE_INPUT
        ws.cell(i, 3, u)


def _sources(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("Sources")
    cols = ["ID", "Document", "Page", "Publisher", "Date", "URL", "Verified"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, s in enumerate(spec.sources, start=2):
        ws.cell(i, 1, s.id)
        ws.cell(i, 2, s.doc).font = BULGE_GREEN_LINK
        ws.cell(i, 3, s.page or "")
        ws.cell(i, 4, s.publisher or "")
        ws.cell(i, 5, s.date or "")
        ws.cell(i, 6, s.url or "")
        ws.cell(i, 7, "✓" if s.verified else "")


def _claims(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("Claims")
    cols = ["Class ID", "Priority", "Description", "Allowed Amount", "Collateral", "Contractual Rate", "Impaired"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, cls in enumerate(spec.claim_classes, start=2):
        ws.cell(i, 1, cls.class_id)
        ws.cell(i, 2, cls.priority)
        ws.cell(i, 3, cls.description)
        ws.cell(i, 4, float(cls.allowed_amount)).font = BULGE_BLUE_INPUT
        ws.cell(i, 5, float(cls.collateral_value) if cls.collateral_value else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 6, float(cls.contractual_rate) if cls.contractual_rate else "").font = BULGE_BLUE_INPUT
        ws.cell(i, 7, "Y" if cls.impaired else "N")

    # Total row
    n = len(spec.claim_classes)
    if n > 0:
        ws.cell(n + 2, 1, "TOTAL").font = HEADER_FONT
        ws.cell(n + 2, 4, f"=SUM(D2:D{n+1})").font = BULGE_BLACK_FORMULA


def _dip(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("DIP")
    if spec.dip_facility is None:
        ws.cell(1, 1, "No DIP facility in this spec.")
        return
    d = spec.dip_facility
    rows = [
        ("Facility size", float(d.facility_size)),
        ("Drawn", float(d.drawn)),
        ("Coupon", float(d.coupon)),
        ("Upfront fee %", float(d.upfront_fee_pct)),
        ("Maturity (months)", d.maturity_months),
        ("Super-priority", "Y" if d.super_priority else "N"),
        ("Primed liens", ", ".join(d.primed_liens) or "—"),
        ("Annual interest cost", f"=B2*B3"),  # B2=drawn, B3=coupon (offset by header)
        ("Upfront fee paid", f"=B1*B4"),     # B1=facility, B4=upfront%
        ("Total period cost", float(compute_total_dip_cost(d))),
    ]
    for i, (k, v) in enumerate(rows, start=1):
        ws.cell(i, 1, k).font = HEADER_FONT if i <= 7 else Font()
        cell = ws.cell(i, 2, v)
        if isinstance(v, str) and v.startswith("="):
            cell.font = BULGE_BLACK_FORMULA
        else:
            cell.font = BULGE_BLUE_INPUT


def _waterfall(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("Waterfall")
    cols = ["Class ID", "Priority", "Allowed", "Recovered", "Recovery %"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT

    results = compute_absolute_priority_waterfall(spec)
    for i, r in enumerate(results, start=2):
        ws.cell(i, 1, r["class_id"])
        ws.cell(i, 2, r["priority"])
        ws.cell(i, 3, float(r["allowed"])).font = BULGE_BLUE_INPUT
        ws.cell(i, 4, float(r["recovered"])).font = BULGE_BLACK_FORMULA
        rec = float(r["recovery_pct"])
        c = ws.cell(i, 5, rec)
        c.font = BULGE_BLACK_FORMULA if rec >= 0.5 else BULGE_RED_WARN


def _plan(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("PlanRecoveries")
    cols = ["Class ID", "Cash", "New Equity %", "New Debt Face", "Recovery %", "Vote Required"]
    for j, c in enumerate(cols, start=1):
        ws.cell(1, j, c).font = HEADER_FONT
    for i, r in enumerate(spec.plan_recoveries, start=2):
        ws.cell(i, 1, r.class_id)
        ws.cell(i, 2, float(r.cash_distribution)).font = BULGE_BLUE_INPUT
        ws.cell(i, 3, float(r.new_equity_pct)).font = BULGE_BLUE_INPUT
        ws.cell(i, 4, float(r.new_debt_face)).font = BULGE_BLUE_INPUT
        ws.cell(i, 5, float(r.recovery_pct) if r.recovery_pct else "").font = BULGE_BLACK_FORMULA
        ws.cell(i, 6, "Y" if r.votes_required else "N")


def _qc(wb: Workbook, spec: RestructuringSpec) -> None:
    ws = wb.create_sheet("QC")
    ws.cell(1, 1, "Check").font = HEADER_FONT
    ws.cell(1, 2, "Result").font = HEADER_FONT

    total_claims = sum(c.allowed_amount for c in spec.claim_classes)
    distributable = (
        spec.enterprise_value_post + spec.cash_at_emergence + spec.new_debt_at_emergence
    )
    if spec.dip_facility:
        distributable -= spec.dip_facility.drawn

    checks = [
        ("≥1 claim class present", "PASS" if spec.claim_classes else "FAIL"),
        ("Total claims > 0", "PASS" if total_claims > 0 else "FAIL"),
        ("EV post > 0", "PASS" if spec.enterprise_value_post > 0 else "FAIL"),
        ("DIP super-priority flagged", "PASS" if (not spec.dip_facility) or spec.dip_facility.super_priority else "PARTIAL"),
        ("Distributable > 0", "PASS" if distributable > 0 else "FAIL"),
        ("≥1 plan recovery defined", "PASS" if spec.plan_recoveries else "PARTIAL"),
        ("Reasonable months in Ch.11 (6-36)", "PASS" if 6 <= spec.months_in_chapter11 <= 36 else "PARTIAL"),
    ]
    for i, (chk, res) in enumerate(checks, start=2):
        ws.cell(i, 1, chk)
        c = ws.cell(i, 2, res)
        c.font = BULGE_BLACK_FORMULA if res == "PASS" else BULGE_RED_WARN
