"""BaseModelSpec protocol — the interface every template implements.

Each template defines:
    - meta: ModelMeta (for Cover)
    - target: Target (for Cover)
    - sources: list[Source] (for Sources sheet)
    - all_assumptions() -> list[Assumption] (for Assumptions sheet)
    - model_type: Literal[...] (for CLI dispatch)

Templates provide their own `build_core_sheets(wb, spec, graph, driver_refs)`
function that emits the template-specific middle sheets (e.g. OperatingModel,
DebtSchedule, Covenants, Returns for Unitranche; BondStructure, CashFlows,
InvestorReturns for Minibond; etc.).

Cover, Sources, Assumptions, QC are shared and auto-generated by the base
workbook builder.
"""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from modelforge.spec.base import Assumption, ModelMeta, Source, Target


@runtime_checkable
class BaseModelSpec(Protocol):
    """Minimum interface every ModelForge template must satisfy."""

    model_type: str
    meta: ModelMeta
    target: Target
    sources: list[Source]

    def all_assumptions(self) -> list[Assumption]:
        ...
